### ISSUE TITLE
NameError: name 'get_ipython' is not defined

### ISSUE THREAD

**Issue by sagunkayastha** [pylabelalpha/package#1]
When running from pylabel import importer
getting following error
`Traceback (most recent call last):
  File "pyl_conv.py", line 1, in <module>
    from pylabel import importer
  File "/home/laanta/anaconda3/envs/sagun_env/lib/python3.8/site-packages/pylabel/importer.py", line 10, in <module>
    from pylabel.dataset import Dataset
  File "/home/laanta/anaconda3/envs/sagun_env/lib/python3.8/site-packages/pylabel/dataset.py", line 4, in <module>
    from pylabel.labeler import Labeler
  File "/home/laanta/anaconda3/envs/sagun_env/lib/python3.8/site-packages/pylabel/labeler.py", line 6, in <module>
    if 'google.colab' in str(get_ipython()):
NameError: name 'get_ipython' is not defined`

**Comment by alexheat** [comment]
Hi thank you for this message. Let me try to help you:
I think you are trying to run one of the notebooks locally. It looks like the error is on this line:
"line 6, in <module> if 'google.colab' in str(get_ipython()): NameError: name 'get_ipython' is not defined"

I think I know what the problem is. The notebook is tested on Google collab and that get_ipython package is not on your machine. I will reseach how I can resolve it.

**Comment by sagunkayastha** [comment]
Thank you @alexheat

**Comment by alexheat** [comment]
@sagunkayastha are you trying to run a notebook locally? Or do you want to run a .py file outside of notebook?

**Comment by sagunkayastha** [comment]
I want to run .py file outside of the notebook

**Comment by alexheat** [comment]
Hi. I think that I fixed the issue. I moved some code that only works in a notebook. 

You will need the latest version of the package
pip install pylabel==0.1.10

I tested it using the commands from this notebook and it worked https://github.com/pylabel-project/samples/blob/main/voc2coco.ipynb.

Also note that this is an old version of the repo that I no longer maintain. This is the new version https://github.com/pylabel-project/. But I can keep helping you on this thread.

**Comment by sagunkayastha** [comment]
Thank you
